### ISSUE TITLE
not an issue, kind of an anti-issue - Windows 11 related

### ISSUE THREAD

**Issue by mutageneral** [torchgm/RoundedTB#10]
Just dropping here to say that RoundedTB works actually very well on the Windows 11 leak and looks stunning!
With:
![image](https://user-images.githubusercontent.com/62779748/122139099-2cbb3200-ce16-11eb-8e1b-cee032257bd7.png)
Without:
![image](https://user-images.githubusercontent.com/62779748/122139187-6724cf00-ce16-11eb-883a-50682c5c06c3.png)

So yeah, don't need to be scared about the changes Windows 11 will bring because looks like it will stay very compatible! The only thing I see is that the date and time is slightly is cut off. Windows 11 is not officially releasing anytime soon anyway, so you can forget about this until then.

**Comment by torchgm** [comment]
No worries! I already tested it and am keeping an eye out. The date and time is only cut off if it's three lines in total (which is default for some regional formats, but can be customised from Settings). Alternatively you can use [T-Clock](https://github.com/White-Tiger/T-Clock) to customise the format of the clock further. This works on build 21996 too.

**Comment by mutageneral** [comment]
Yes, tanks! I combined the use of RoundedTB, T-Clock and TaskbarX to get this even better result!
![image](https://user-images.githubusercontent.com/62779748/122301284-7c5d3480-cece-11eb-8f5f-3ae828926e2e.png)

> The date and time is only cut off if it's three lines in total (which is default for some regional formats, but can be customised from Settings).

I read on a [forum](https://windowsonwindows.com/forum/viewtopic.php?f=18&t=30&p=56#p56) that on Windows 11 _"the triple-decker clock is on by default for everyone when under 96dpi and goes back to a double-decker clock if you use a higher DPI."_

**Comment by torchgm** [comment]
Worth noting that I wouldn't recommend using TBX on 11; it fails to find the handles its looking for (due to the changes to the taskbar) and becomes relatively unstable. I'd recommend using [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) free from the Store which works fine and offers more customisation options in terms of the visual composition of the taskbar.

> I read on a forum that on Windows 11 "the triple-decker clock is on by default for everyone when under 96dpi and goes back to a double-decker clock if you use a higher DPI."
Yeah, this is my bad; I initially assumed it was a regional thing due to my testing but I can confirm it's now scaling after I tested it on some other machines.

**Comment by mutageneral** [comment]
> Worth noting that I wouldn't recommend using TBX on 11; it fails to find the handles its looking for (due to the changes to the taskbar) and becomes relatively unstable. I'd recommend using [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) free from the Store which works fine and offers more customisation options in terms of the visual composition of the taskbar.

Strange because I actually tried translucent tb first and that one had a problem with the blur mode which would actually just take a screenshot of what is underneath the taskbar and so if you put a window under the taskbar you would not see it. I think there was something else but can't remember, maybe something to do with how the acrylic mode looked like?

Your right tho, I did have visual glitches like the taskbar flashing and the icons disappearing after the screen flashes black (but I think the second one is due to vmbox drivers).

**Comment by torchgm** [comment]
The taskbar itself hasn't really changed (it's still the same window class and fundamentally works the same), so I'd probably blame weird glitched appearance on VM graphics drivers. Works fine on hardware for me.
