### ISSUE TITLE
RoundedTB doesn't work with Auto-hide Taskbar 

### ISSUE THREAD

**Issue by Qubisted** [torchgm/RoundedTB#103]
When enabling dynamic mode and auto-hide taskbar, the new dock/taskbar does not show up on hover

**Comment by torchgm** [comment]
Duplicate of too many issues to count but yep this isn't supported at the moment (and never really will be). Autohide directly interferes with how RoundedTB works. I'll be working on a custom autohide feature for a future update to address this.

**Comment by TechStudent11** [comment]
@torchgm Is it in the canary version? If so, I would happily test it out. I would really love this feature!
