### ISSUE TITLE
useless on windows 11

### ISSUE THREAD

**Issue by fisforfaheem** [torchgm/RoundedTB#108]
wont work by default...has to change settings in advanced..also that goes away after some time

**Comment by torchgm** [comment]
You're going to have to elaborate on what you mean; screenshots etc.?

**Comment by fisforfaheem** [comment]
sorry i have deleted it now ..really sorry



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/17/21,
04:08:57 AM
