### ISSUE TITLE
Left part of taskbar is not right

### ISSUE THREAD

**Issue by kubuntuclaps** [torchgm/RoundedTB#109]
Build: Latest release (3.1)
Windows: Windows 11 21H2 (22000.318)

Look at my taskbar, if you need more details tell me
<img width="1919" alt="bug" src="https://user-images.githubusercontent.com/56472448/142064971-539ae00f-853e-4e84-96ba-318151500753.png">

**Comment by torchgm** [comment]
i hate this bug so much - it was supposed to be fixed in R3.1.

Set the taskbar icons to the left then back to the centre - that should restore it.

**Comment by diego-toro** [comment]
Just so you know I just installed RoundedTB v3.1 on my new PC and I still have this bug
![Screenshot 2021-11-20 113157](https://user-images.githubusercontent.com/5667514/142733894-c4ebff52-1241-49ed-8860-6e5cca26f506.png)
Moving the icons to the left and center them back works tho.
