### ISSUE TITLE
Dynamic mode only effective on right side. Odd graphics

### ISSUE THREAD

**Issue by Keith94** [torchgm/RoundedTB#110]
left side of Taskbar still has background visible

![Screenshot 2021-11-17 180710](https://user-images.githubusercontent.com/5490615/142338355-40db7a96-1fe6-463a-9a30-9afb34064af7.png)

**Comment by Peedee2002** [comment]
hey check out https://github.com/torchgm/RoundedTB/issues/98
tldr you can fix this bug by setting your taskbar to the left then centre again - should only need to be done once. The maintainer says he will try to look into this.

**Comment by Keith94** [comment]
Thx
