### ISSUE TITLE
Windows 11: The taskbar's left side is unresponsive after sleep, until roundedtb is opened

### ISSUE THREAD

**Issue by SlavBoi420** [torchgm/RoundedTB#111]
I use the taskbar docked, using RoundedTB. I enabled the options to show the right side on hover. However, after waking up from sleep, the right side won't come up on hover, and the apps opened gets cut off by the dock, as the icons push each other away, when an app is opened. This usually gets fixed when RoundedTB is opened. I also use TransluscentTB integration.

**Comment by torchgm** [comment]
I'm aware of this bug and not entirely sure why it crops up for some people but not others. I'll keep looking for a solution (which would be made easier if I could reproduce it myself lol)
