### ISSUE TITLE
[Bug] RoundedTB not working on second monitor- Windows 11

### ISSUE THREAD

**Issue by notRyuk** [torchgm/RoundedTB#116]
# Taskbar when an app is running in full screen mode( I have multiple displays setup and its happening for both the diplays)

## When the browser I'm typing this issue from is in full screen
![image](https://user-images.githubusercontent.com/72451243/143479698-30fc7040-2aee-4182-87fa-4b11de9d58d6.png)
### My RoundedTB settings:
![image](https://user-images.githubusercontent.com/72451243/143479784-267c485b-f711-40a0-ba99-53316cbcfb53.png)

## When the same browser which is now in minimized mode
![image](https://user-images.githubusercontent.com/72451243/143480032-add2d66b-e8f5-4846-bf37-394cc9fd581d.png)
### My RoundedTB settings
Same as above

### My taskbar settitings
![image](https://user-images.githubusercontent.com/72451243/143480277-9cd11c1d-f33a-4508-917a-b52cf994bbb1.png)

*Edit*
Just found that the RoundedTB not getting applied on the second display even if something is open either minimized or maximazied in any of the displays (This is browser is open in minimized mode on the first display and same is happening with maximized mode or nothing)
![image](https://user-images.githubusercontent.com/72451243/143480983-381b6c7e-6dd2-4f87-a14c-9a6844fdc5d3.png)

**Comment by dongle-the-gadget** [comment]
Well regarding Dynamic Mode not working when a window is maximized, it is due to you enabling "Fill taskbar when maximized".

**Comment by notRyuk** [comment]
> Well regarding Dynamic Mode not working when a window is maximized, it is due to you enabling "Fill taskbar when maximized".

Oh thanks but the Multiple monitor problem still exists

**Comment by dongle-the-gadget** [comment]
> > Well regarding Dynamic Mode not working when a window is maximized, it is due to you enabling "Fill taskbar when maximized".
> 
> Oh thanks but the Multiple monitor problem still exists

Idk if Dynamic mode currently supports multiple monitors.

**Comment by notRyuk** [comment]
Yeah have to wait and see

**Comment by torchgm** [comment]
Dynamic mode should work on multiple monitors and RoundedTB is clearly making changes to the second monitor - could you try setting the taskbar icons to the left to see if that makes a difference?

**Comment by notRyuk** [comment]
> could you try setting the taskbar icons to the left to see if that makes a difference?

![image](https://user-images.githubusercontent.com/72451243/144006343-9455071e-67a7-43fb-bb17-d712d7392282.png)

Its the same

**Comment by hastostron** [comment]
> > could you try setting the taskbar icons to the left to see if that makes a difference?
> 
> ![image](https://user-images.githubusercontent.com/72451243/144006343-9455071e-67a7-43fb-bb17-d712d7392282.png)
> 
> Its the same

Have you found any fix? it was working for me but now its not

**Comment by sandercoffee** [comment]
Any updates?

**Comment by hastostron** [comment]
NOPE

**Comment by bcarpio** [comment]
Having the same issue.

**Comment by notRyuk** [comment]
> Having the same issue with multiple monitors.
Yeah the multiple monitor issue has not been fixed yet.




> Any updates?
![image](https://user-images.githubusercontent.com/72451243/224574626-adc55651-c9cc-4db5-9a8c-e5944752bede.png)
yeah with these settings. this is was after applying the settings and restarting.

**Comment by hastostron** [comment]
It's working now.

**Comment by Cedar3702** [comment]
Also am having the same issue on my second monitor
