### ISSUE TITLE
Corners are very pixelated. 

### ISSUE THREAD

**Issue by therealzamdoms** [torchgm/RoundedTB#120]
The corners of the taskbar are not smooth. the visual is very pixelated and it ruins the whole experience. attaching a picture to show what I mean. pls fix in the next update. thank you! loving it otherwise. 
<img width="98" alt="image" src="https://user-images.githubusercontent.com/95126658/143677879-7dfecf9d-4678-4080-88ec-c9a2d0aec6ce.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/95126658/143677911-442ec9f3-604d-4467-aebe-52606b344647.png">

**Comment by dongle-the-gadget** [comment]
Yeah those are due to Windows not having antialiasing support for `CreateRoundRectRgn`.

**Comment by mobeicanyue** [comment]
> CreateRoundRectRgn

it's windows's question,not this software

**Comment by dongle-the-gadget** [comment]
> > CreateRoundRectRgn
> 
> it's windows's question,not this software

It's a Windows limitation as it is said.

**Comment by mobeicanyue** [comment]
> > > CreateRoundRectRgn
> > 
> > it's windows's question,not this software
> 
> It's a Windows limitation as it is said on README.

Yes, isn't that what I meant?

**Comment by torchgm** [comment]
There is no way to fix this with how RoundedTB works currently, and there's no plan to adjust how RoundedTB works at this point.
