### ISSUE TITLE
Dynamic mode does not work on dual monitors

### ISSUE THREAD

**Issue by fabi229** [torchgm/RoundedTB#121]
Release 3.1 (v1.3.1.0)

The Dynamic Mode function isn't working properly right now on dual monitors.

For some reason, it's stretching the left side of the bar.

**Monitor 1**
<img width="960" alt="Monitor_1" src="https://user-images.githubusercontent.com/32079092/143723799-74ccc732-edb3-4578-aea0-0a2626723c2a.png">

**Monitor 2**
<img width="960" alt="Monitor_2" src="https://user-images.githubusercontent.com/32079092/143723800-9d798a27-8196-4106-b5f6-bd888afad64c.png">

**Comment by torchgm** [comment]
Set the taskbar icons to the left then back to the centre and the isse will be resolved. This bug will be fixed in the next update.

**Comment by fabi229** [comment]
Thank you very much!

It worked :DD
