### ISSUE TITLE
Maximised app

### ISSUE THREAD

**Issue by claymorwan** [torchgm/RoundedTB#122]
The dynamic mod is very cool, but when I wanted to keep in maximised app, it don't look very good. My idea is to expend the maximised application to reach the bottom of the screen, like that :
![roundedtb-feature_idea](https://user-images.githubusercontent.com/86072589/143724213-efe54826-1e3a-4e7c-a17d-58960e6608e6.jpg)

**Comment by torchgm** [comment]
This is a planned feature and will be available in the next major update.
