### ISSUE TITLE
Dynamic mode not working properly

### ISSUE THREAD

**Issue by HUMENTH** [torchgm/RoundedTB#125]
Windows 11 OS Build 22504.1010
![image](https://user-images.githubusercontent.com/4609678/144282261-c7c96e4c-f122-4f4f-8ccb-413f9f762aa9.png)
![image](https://user-images.githubusercontent.com/4609678/144282434-43cc26fb-a7a0-4c0c-b594-dbd78b9f3f46.png)

**Comment by m-schmale** [comment]
Unfortunately, I've got the same problem.

**Comment by iizaitounii** [comment]
same here

**Comment by ramvignesh-b** [comment]
Taskbar Settings -> Alignment -> Change to Left and switch back to Centre.
Worked for me :)

**Comment by m-schmale** [comment]
@ramvignesh-b Thanks a lot, it's working. 👍

**Comment by ebdonato** [comment]
> Taskbar Settings -> Alignment -> Change to Left and switch back to Centre. Worked for me :)

[@ramvignesh-b](https://github.com/ramvignesh-b), thank you! It's working.

**Comment by Aadhino01** [comment]
> Taskbar Settings -> Alignment -> Change to Left and switch back to Centre. Worked for me :)

Thank you bro

**Comment by Erisa** [comment]
As mentioned, can be fixed with changing alignment to leeft and then back agaain.

Closing because this is being tracked in #98
