### ISSUE TITLE
[Feature Request][Implementation Bounty] Add toggle to hide the Start Menu button

### ISSUE THREAD

**Issue by xNul** [torchgm/RoundedTB#128]
Hey all!

In my opinion, Windows 11 is a great operating system aside from the Start Menu. To fix that blemish, increase productivity, and improve aesthetics, I've started using PowerToy Run + PowerToy Keyboard Manager (rebind WinKey to PowerToy Run) + RoundedTB + TranslucentTB and so far it works great! I think Windows 11 + this config is the best Windows experience I've ever had, but there is one problem: the Start Menu button.

![image](https://user-images.githubusercontent.com/894305/144462686-fb754f08-1005-49c9-9429-d6253392b45f.png)

With this setup, there is no reason to have the Start Menu! PowerToy Run does everything you'd want the Start Menu to do so there is a useless icon/button on the taskbar for a Start Menu you don't even use! Ideally, some tool would be able to hide it but I can't find one anywhere. StartIsGone and Start Killer are tools that do this for earlier versions of Windows but both projects are inactive and I doubt they will update to support Windows 11. I'd implement the tool myself, but I have no experience in this area.

I ask that RoundedTB or someone in the community makes this tool/feature. To help out, I'll contribute $10 to whoever implements it. Maybe this issue can double as a bounty thread for the feature, similar to what is done in the XDA Forums.

**Comment by torchgm** [comment]
I mean I can tell you for a start that it's not particularly easy - the Start button is embedded in the taskbar's XAML layer and basically inaccessible without proper XAML debugging, which isn't really a thing at the moment. Even if you did delete the Start button, the centring of the taskbar wouldn't compensate for it. RTB *could* just crop the Start button out but then the taskbar would always be off-centre.

It's technically possible but out-of-scope for RoundedTB I'm afraid.

**Comment by xNul** [comment]
@torchgm thanks for the response! Is it not possible to, after cropping out the start menu, to repaint it such that it is center once again?

Do you have any place you'd suggest posting this feature request? Is there a Windows UI modding forum somewhere? Another open source tool which may be able/willing to implement this?

Thanks for your work on RoundedTB!
