### ISSUE TITLE
[Feature request] Add the option to change individual corner radiuses 

### ISSUE THREAD

**Issue by link6155** [torchgm/RoundedTB#129]
Being able to customize each corner radius rather than having them all be the same would be nice. Example of what I mean (top corners rounded while bottom ones are not):
![image](https://user-images.githubusercontent.com/1360980/144662967-573b9ba0-3d27-496c-9a3d-2ebb6175a7af.png)

**Comment by torchgm** [comment]
You can already achieve this with the advanced margins (the ... icon) and then specifying a negative margin in the side you want to "remove" the rounded corners from (-100 is usually what I use). There's no way for me to make the corners actually individually adjustable without a significant overhaul and a lot of introduced latency, but just having a negative margin usually achieves the look that most people are after.

Some examples:
![image](https://user-images.githubusercontent.com/31840547/144666376-f6a09408-a864-4d17-991b-a09b1fd7be79.png)

![image](https://user-images.githubusercontent.com/31840547/144666617-57f04b33-29c0-48a8-a054-e27c713c3a7e.png)

![image](https://user-images.githubusercontent.com/31840547/144666723-51d61e68-ff82-45ba-8f5f-fbbb8991c75c.png)

I do realise that this isn't particularly-well-documented but they are an advanced feature so for R3 it seemed fine. I'm working on overhauling the UI entirely at which point there will be checkboxes for this behaviour instead.

**Comment by link6155** [comment]
@torchgm Thanks for the tip. I still do think individual rounded corners would be a nice feature. I could see some interest aesthetics by doing so:
![rounded_custom](https://user-images.githubusercontent.com/1360980/144939240-da678334-6d9a-49ba-849e-0bfd545056ec.png)
