### ISSUE TITLE
Closes when going to sleep

### ISSUE THREAD

**Issue by nolemretaWxd** [torchgm/RoundedTB#132]
When I put my laptop to sleep mode, and use it again after sometime, RoundedTB is not running.

Steps to reproduce:
1. Put your device to sleep mode
2. Wake it up after some time
3. RoundedTB will close

Expected behaviour:
RoundedTB should be running

OS version: Windows 11 22000.318
RoundedTB version: 3.1

**Comment by Erisa** [comment]
When this happens, are you able to check Event Viewer to see if there are any Application errors listed?

Can you also try this:
> Close RoundedTB, then try deleting the config file at `%localappdata%\rtb.json` (or if you're using the Store version, the delete the file at `%localappdata%\Packages\14082CryzenTechnologies.RoundedTB_6b5yntewjra3r\RoamingState\rtb.json`).
Re-open it, see if it launches.
