### ISSUE TITLE
[Bug] Not able to open taskbar - Windows 11

### ISSUE THREAD

**Issue by notRyuk** [torchgm/RoundedTB#133]
Not able to open taskbar when RoundedTB is running on the seconding 
- Taskbar settings
![image](https://user-images.githubusercontent.com/72451243/145410367-f582f560-4e21-4f86-b24e-32a6f214acb8.png)
- RoundedTB settings
![image](https://user-images.githubusercontent.com/72451243/145410593-36d4fc76-f25c-4466-8147-d06f03eee621.png)

Without Auto Hide settings:
![image](https://user-images.githubusercontent.com/72451243/145410838-c3f12c74-a651-46d8-bdb5-1c930f522940.png)

With Auto Hide enabled:
![image](https://user-images.githubusercontent.com/72451243/145410955-0fc1535a-dd9b-46ff-a27e-1c0ce5a0d5e1.png)

https://user-images.githubusercontent.com/72451243/145411778-469069a2-d7c1-4339-a338-e6f228dac04c.mp4

**Comment by torchgm** [comment]
Windows' autohide is currently not supported and never will be due to technical limitations. I'm working on a custom autohide that will have a few extra customisation options, which will be available in the next major update.

**Comment by notRyuk** [comment]
Ahh thanks
