### ISSUE TITLE
WIndows 11 - Dynamic Mode not applied to second monitor 

### ISSUE THREAD

**Issue by iieuphoria** [torchgm/RoundedTB#136]
Rounded taskbar seems to work fine all round in win 11 however seems that it doesn't apply dynamic mode to the second monitor when the taskbar is set to auto-hide

https://user-images.githubusercontent.com/95953059/145788502-503e5762-c452-4dd5-b0c0-152707616644.mp4

**Comment by iieuphoria** [comment]
also I forgot to mention thankyou for sharing this awesome little utility with us!

**Comment by notRyuk** [comment]
same as my issue #116

**Comment by notRyuk** [comment]
But since ur using auto hide taskbar its having some issue which will be fixed in next major update #133 it works fine when auto hide setting is off tho

**Comment by Erisa** [comment]
Closing in favour of #116 and #36
