### ISSUE TITLE
Options windows bugging out.

### ISSUE THREAD

**Issue by NukeThief** [torchgm/RoundedTB#139]
Windows 11 21H2 Build: 22000.34
![Zrzut ekranu 2021-12-14 164148](https://user-images.githubusercontent.com/81801547/146030641-1fb0e803-451f-4951-ad46-4d9882b4fa72.png)
8

**Comment by torchgm** [comment]
This is a graphical issue independent of RoundedTB - make sure your GPU drives are up-to-date and that you have no other pending updates.
