### ISSUE TITLE
RoundedTB Store application issue: Margin not going after uninstallation

### ISSUE THREAD

**Issue by subhajitnandi** [torchgm/RoundedTB#14]
I have recently installed RoundedTB application from MS Store, so that I can customise the taskbar. I applied Margin and Corner radius but not looking so much good, so I have uninstalled it.

After restart my PC, I have noticed rounded corner gone, but margin still there in taskbar, value is 1. For fixing this issue I have reinstalled the application from MS Store again, and then when I launch the application, I noticed taskbar become normal, no margin.

I thought problem was gone. So, I have uninstalled the application again and restarted my machine. Problem appeared again. Now I do not know how do I going to fix this issue. You can check my given screenshot below, a small margin below taskbar and right corner you can notice.

Please help me to get rid of it.

![Screenshot 2021-06-23 011529](https://user-images.githubusercontent.com/46860380/122992715-0e2fda80-d3c4-11eb-9275-3de8c94b23d9.png)

**Comment by torchgm** [comment]
There shouldn't be (nor can I recreate) any behaviour that causes it to affect anything after its removed and the taskbar is recreated (either by restarting Explorer or Windows). In fact, it's impossible for that to be the case. Furthermore, it appears that the margin is only present on two sides which was a bug in version R1 (which was never on the Store). Make sure you haven't got any versions from GitHub running. These older builds will have this icon:
![image](https://user-images.githubusercontent.com/31840547/122998353-d5ccd400-d3a4-11eb-9e12-ace0f058c08b.png)

Check in the system tray and in Task Manger > More details > Start-up for this icon and RoundedTB. Make sure it's not running on startup and then reboot.

If you find nothing at all, then redownload the Store version, set both values to 0, click apply, then right-click the tray icon > Close RTB. You can then uninstall it. However, I don't think this is necessary as it seems you're just running an older version of the software alongside the Store version.

**Comment by subhajitnandi** [comment]
I have uninstalled after using this application from Store. I did not download it from GitHub version.

However, when I am downloaded the application again from Store and launch the application, taskbar restored as it was default. But when I closed the application and restart the Explorer from Task Manager, problem occurred again. But still application not running.

**Comment by torchgm** [comment]
Then it sounds like something else is interfering if you're 100% sure it's not running. RoundedTB has to apply the changes every time the taskbar appears, so if it's not installed and the taskbar is recreated (such as if you restart your PC or Explorer) there is no way that it can apply the changes. RoundedTB doesn't (and can't) touch any system files so once you've uninstalled it and rebooted your system should be fundamentally identical to before you ever installed it.

I can't help you further if this issue is still appearing after it's been removed and the system has been rebooted because there's really no way that it could continue to alter the taskbar past that point.

**Comment by subhajitnandi** [comment]
Okay, thanks for your help.

**Comment by fareloz** [comment]
I have the same issue. I applies some margin and radius. After uninstallation and restart of pc it's applied again. How to get rid of it?

**Comment by torchgm** [comment]
I mean, I can't help you - RTB doesn't install any services, or apply any lasting changes. Try `taskkill /f /im roundedtb.exe` and see if it kills anything. If it does then the Store failed to uninstall it for some reason. If it doesn't, then it's not running and it's either an incredibly funky bug or another bit of software implementing something similar (TaskbarX, for example).

**Comment by fareloz** [comment]
@subhajitnandi it is a the TaskbarX, download latest release to fix it: https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.7.1.0

**Comment by torchgm** [comment]
Yep, seems to have been caused by TaskbarX - https://github.com/ChrisAnd1998/TaskbarX/issues/682
