### ISSUE TITLE
[BUG] icons out of the task bar

### ISSUE THREAD

**Issue by freshjh** [torchgm/RoundedTB#141]
![image](https://user-images.githubusercontent.com/70044642/147083581-838ddec0-31e9-409e-a569-1a142439206c.png)
As the image shows, the icon of "Pictures" out of the range of task bar, as the "Pictures" program not set  to  fixe at the task bar.

**Comment by torchgm** [comment]
Make sure you have the latest version of TranslucentTB installed, and you have the "TranslucentTB compatibility" option enabled.

**Comment by freshjh** [comment]
Thanks for your timely reply. I tackled this problem by following your suggestion. It is a nice tool.
