### ISSUE TITLE
Join Taskbar and System Tray as One Dock

### ISSUE THREAD

**Issue by Spinnekop** [torchgm/RoundedTB#143]
Nice app - Perhaps an option to have one central dock with system tray joined to taskbar?

**Comment by torchgm** [comment]
I've experimented with this before, but unfortunately it's not really possible at the moment.

Attempting to move the taskbar appicons or notificationarea at all often breaks the Start menu and prevents it from opening, and also the tray has a stupid issue where it just likes to pretend that it's the width of the entire monitor and without knowing how wide it is, there's no way to centre it reliably

I'll close this issue for now but if I ever revisit it with some fancy new method that'd be less buggy, then I'll re-open it.

**Comment by Spinnekop** [comment]
It's easy in the world of linux my friend! 🐧🐧🐧 Cheers.
