### ISSUE TITLE
RoundedTB on Dynamic mode does not hide left side of Task Bar

### ISSUE THREAD

**Issue by Aadhino01** [torchgm/RoundedTB#145]
![image](https://user-images.githubusercontent.com/96899083/147802325-388ec9c3-8cb5-4ffd-8021-dfbfc15ef413.png)

**Comment by TheDiamondGen** [comment]
Settings > Personalization > Taskbar > taskbar behavior > Center to Left
And switch from Left to Center again
This is a known issue and has been posted many times.

**Comment by Aadhino01** [comment]
> Settings > Personalization > Taskbar > taskbar behavior > Center to Left And switch from Left to Center again This is a known issue and has been posted many times.

Thank you so much it worked.

**Comment by Erisa** [comment]
Can be fixed with the workaround above if anyone is coming across this issue.

Duplicate of #98 so closing
