### ISSUE TITLE
Doesn't play nice with Taskbarx anymore for Windows 11 look on Windows 10

### ISSUE THREAD

**Issue by privacyguy123** [torchgm/RoundedTB#146]
Title says it all - TaskbarX seems to override what RoundedTB is doing.

**Comment by torchgm** [comment]
This is an issue with TaskbarX, not RoundedTB - you'll have to go and file an issue over there if you've not already. It's not a taskbar mod I support (for many reasons) but an upcoming update will expand compatibility and might help a bit, no ETA or guarantees on that though.
