### ISSUE TITLE
Feature Request: Add Drag and Drop files through taskbar

### ISSUE THREAD

**Issue by FuriousGH** [torchgm/RoundedTB#149]
Add Drag and Drop files through taskbar. This was removed in Win11 so to have it in this would be great.

**Comment by torchgm** [comment]
This is out-of-scope for RoundedTB I'm afraid, but you can use [this](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix) which does exactly what you're asking.
