### ISSUE TITLE
Extra Padding/Margin Options

### ISSUE THREAD

**Issue by iRhysLee** [torchgm/RoundedTB#15]
I wondered if it was possible to have an option for separate padding adjustments. I'd love to be able to bring the sides of the taskbar in but keep the smaller padding at the bottom.
I am also curious if there is a way to shift the entire taskbar, like move it further away from the bottom of the screen without changing the padding/size.

Thank you very much.
![image](https://user-images.githubusercontent.com/47948838/123701810-3e5ef980-d85a-11eb-87eb-545537997944.png)

**Comment by torchgm** [comment]
Independent margin options are something I'm going to try and add at a later stage, however moving the taskbar in any way is out of the question. Windows outright blocks any application from doing so. Honestly the fact that I can even do what I'm currently doing with it is pretty amazing to me. If it suddenly becomes possible to do so though then I will.

**Comment by iRhysLee** [comment]
Thanks for the response! I eagerly await having independent margins as that will be the finishing touch to my setup. I appreciate all the work you're doing with this. 
Yeah I wasn't sure if being able to move the taskbar would be possible so I thought I'd ask. Either way, I love the work so far and will continue to support it. :)

**Comment by awesomelewis2007** [comment]
#15

**Comment by torchgm** [comment]
This feature has been superseded by #12 for now, but I have got the code for manually setting margins. Next release will be R3.0 but for R4.0 I want to redo the settings a bit and I'll probably see if I can implement this then.
