### ISSUE TITLE
设置自动隐藏任务栏后，鼠标放在任务栏位置不能自动显示任务栏

### ISSUE THREAD

**Issue by walk-in-cloud** [torchgm/RoundedTB#157]
操作系统是win11 beta版，rounded TB是最新的R3.1
在设置中勾选了 自动隐藏任务栏后，除非按window键，否则无法使用任务栏

**Comment by torchgm** [comment]
当前不支持自动隐藏。 下一个主要更新中将提供自定义自动隐藏功能。
