### ISSUE TITLE
The RoundedTB icon color doesn't respect the taskbar colorscheme.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [torchgm/RoundedTB#16]
![image](https://user-images.githubusercontent.com/13170204/123769968-20c97880-d8ca-11eb-95d7-574343053e48.png)
![image](https://user-images.githubusercontent.com/13170204/123770329-83227900-d8ca-11eb-9653-55a1ee75ceb6.png)

Here's a quick look at my notification bar, you can notice at the forth place starting from the left, the roundedTB icon, being black.
Sadly, relaunching RoundedTB in case of a missed synchronisation doesn't make the icon white again.
So, if this isn't just an automatisation issue, maybe a simple entry to force white or dark icon on it.
_I can also hide those icons out of here obviously._

**Comment by PoorPocketsMcNewHold** [comment]
I believe the issue is specifically due to the theme color, and accentuation choice if it applies or not on the taskbar, as I've managed to find when using a dark colored theme instead of a white one, but a dark taskbar.

**Comment by torchgm** [comment]
I'm aware this icon can be out-of-sync, its implementation was a last-minute thing and not really finalised. This should be fixed in the next release whenever work stops murdering me and I have the time to sit down and finish implementing things.

**Comment by torchgm** [comment]
Turns out this wasn't fixed in the next release because I entirely forgot it was an issue. I promise I won't forget it this time!

**Comment by torchgm** [comment]
Actually fixed in R3.1
