### ISSUE TITLE
When will we see the new version?

### ISSUE THREAD

**Issue by mobeiCanyue** [torchgm/RoundedTB#162]
It's been too long since the update, when will we see the new version?

**Comment by Erisa** [comment]
When its ready. 

Or, to put it another way:
![image](https://user-images.githubusercontent.com/14004943/150666510-cf844bf0-58d4-47f5-8d91-cbb34b3ea08a.png)

Either way I don't think this is appropriate for a GitHub Issue, these are mainly for discussions about features and bugs.
