### ISSUE TITLE
Works great on Winodws 11,is it possible to make the taskbar float?

### ISSUE THREAD

**Issue by Lesliexlau** [torchgm/RoundedTB#17]
Is it possible to make the taskbar float? The bottom margin effct is very strange now on fullscreen mode.
![image](https://user-images.githubusercontent.com/45028523/123891482-8d587c00-d98b-11eb-967c-95e319dae3b6.png)

**Comment by torchgm** [comment]
No, the taskbar cannot be moved by third-part applications. The only option I have is to crop from the edges. In a future update you'll be able to crop independently from each side of the taskbar, so you can have no gap at the "top" if you'd like.
