### ISSUE TITLE
abnormal work

### ISSUE THREAD

**Issue by WindyMadman** [torchgm/RoundedTB#170]
It is running abnormally on Windows11 22000.434, and the left side of the taskbar Windows micro-icon is hidden and does not work properly!

**Comment by Erisa** [comment]
Can you show a screenshot? Is it the same as #98?

**Comment by WindyMadman** [comment]
![image](https://user-images.githubusercontent.com/22683776/152708285-dde45184-68b6-4f64-9599-d7c2a550382c.png)

**Comment by WindyMadman** [comment]
Sorry, this question seems to be the same as his.

**Comment by Erisa** [comment]
Can you confirm whether it gets fixed if you to go to Windows Taskbar Settings and change alignment to Left and then back to Center?

**Comment by Erisa** [comment]
Unless your taskbar is intentionally left? It's hard to tell.

**Comment by WindyMadman** [comment]
> 



> Unless your taskbar is intentionally left? It's hard to tell.

Oh! Thanks a lot, it works fine after doing this.
