### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Mastermoksh999** [torchgm/RoundedTB#177]
It is only working for one side but for the left side it does not change anything how  would i fix this i am on windows 11

**Comment by Erisa** [comment]
Hi, this has been reported and discussed in #98

To resolve it, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".

The next update to RoundedTB will hopefully include a permanent fiix.

**Comment by Mastermoksh999** [comment]
Yep thanks that did it
