### ISSUE TITLE
Showing the left panel on dynamic mode

### ISSUE THREAD

**Issue by yxnchen** [torchgm/RoundedTB#178]
Hi

I have used RoundedTB for a while and think it is an awesome tool.

As Microsoft released the new update (KB5010414) for Windows 11 stable channel a few days ago, the widgets panel was moved to the left. 
![before](https://user-images.githubusercontent.com/8400698/154628075-bfc11875-55c6-4f43-95ff-67ebad766d8b.png)

However, when applying dynamic mode, the left side of the taskbar cannot display. I think it would be great to add this feature to the next release version.
![after](https://user-images.githubusercontent.com/8400698/154628074-ee857c31-e9d7-47dd-b588-dc3898ee1ef8.png)

Current installed version: 3.1

**Comment by Erisa** [comment]
Hi, this is known and tracked in #138

Hopefully the next update will add support for this, right now it isnt supported because of that icon being so new.
