### ISSUE TITLE
Windows 11 Clock on Secondary Screens

### ISSUE THREAD

**Issue by TheGrai** [torchgm/RoundedTB#179]
With the new update to windows 11, we now have the option to have the clock displayed on our secondary screens. Using RoundedTB it will not display the clock. However, if "fill taskbar when maximized" is clicked you will be able to see the normal task bar which now includes the clock. Though this only shows when you have a maximized window.

It would be good to update RoundedTB to have multi monitor support for the data and time.

**Comment by Erisa** [comment]
Hi, this is known and tracked in #138

Hopefully the next update will add support for this, right now it isnt supported because of that icon being so new.
