### ISSUE TITLE
Auto-Hide taskbar breaks RoundedTB

### ISSUE THREAD

**Issue by TermitCG** [torchgm/RoundedTB#18]
When Auto-Hide taskbar is enabled, RoundedTB just doesn't work.

**Comment by torchgm** [comment]
[Seems to be working fine for me](https://torch.is/sending-you-a/BeigeInternationalGoldeneye.mp4). This feature was marked as in beta but I've not had too many issues with it. Can you provide replication steps, a screen recording of behaviour and any other taskbar mods you have installed?

**Comment by torchgm** [comment]
Closing as there's been no update, and this entire feature is being reworked; see #36
