### ISSUE TITLE
Dynamic mode hides the widget menu when it's on the left

### ISSUE THREAD

**Issue by Squareheron942** [torchgm/RoundedTB#181]
In fullscreen (where the taskbar is fully shown) the widget thingy on the left is shown.
![image](https://user-images.githubusercontent.com/82814680/155386984-fe0664c6-c012-4f1f-b64c-5ea4b2a1ba29.png)
But on the desktop it's hidden 
![image](https://user-images.githubusercontent.com/82814680/155387665-030e8bcd-ac25-4c26-a8ca-f1d18ff7dd9d.png)

Pressing Win + F2 and hovering over where it should be doesn't reveal it either.

**Comment by Erisa** [comment]
This is being tracked in #138, and will be addressed in the next update (R4)
