### ISSUE TITLE
Dynamic mode doesn't support new widget (22000.527)

### ISSUE THREAD

**Issue by PlAn-K** [torchgm/RoundedTB#183]
RoundedTB Off
![First](https://user-images.githubusercontent.com/21980585/155513646-d5c90149-7b25-4183-a3b2-8e4be4c2a04a.png)

RoundedTB On (with Dynamic Mode)
![Second](https://user-images.githubusercontent.com/21980585/155513681-eb129779-b45e-4b98-bec5-82a8100f0501.png)

**Comment by PlAn-K** [comment]
RoundedTB Off
![First](https://user-images.githubusercontent.com/21980585/155513646-d5c90149-7b25-4183-a3b2-8e4be4c2a04a.png)

RoundedTB On (with Dynamic Mode)
![Second](https://user-images.githubusercontent.com/21980585/155513681-eb129779-b45e-4b98-bec5-82a8100f0501.png)

**Comment by torchgm** [comment]
This is being tracked in #138 and is already present in the Canary builds.
