### ISSUE TITLE
Taskbar Bug Flickering (TranslucentTB Compatibility)

### ISSUE THREAD

**Issue by LukieEdward** [torchgm/RoundedTB#185]
When are you going to fix the Flickering bug with TranslucentTB?

**Comment by torchgm** [comment]
There's no way to fix that, it's an issue caused by Windows, not TranslucentTB or RoundedTB. There *might* be some progress on this in the future since it looks like the taskbar styling is changing in upcoming Windows 11 builds however. Until then though, nothing I can do I'm afraid 🤷
