### ISSUE TITLE
Stopped working after last Windows 11 update

### ISSUE THREAD

**Issue by erad2008** [torchgm/RoundedTB#186]
Stopped working after last Windows 11 update. Hoping it will be fixed soon as I really enjoyed using it. Cheers

**Comment by Erisa** [comment]
Please can you explain and show what is not working?

**Comment by erad2008** [comment]
Hi, it simply loads every time you run it but then if you try to move mouse over the taskbar icon it simply vanishes. I am using Windows 21H2 Build 22000.527. Cheers

**Comment by erad2008** [comment]
I have also tried starting with fresh copy of program and same thing happens. I am using in conjunction with Translucent Taskbar which is still working.

**Comment by aizuchan** [comment]
This also happened to me but I can't remember what update made it simply vanishes itself. (and didn't bother to test until later
I am currently on 21H2 Build 22000.527 (latest) as well. Can confirm the same behavior happens to me as well. (Fresh install)

**Comment by erad2008** [comment]
Glad to know it is not just me. Cheers.

**Comment by torchgm** [comment]
Close RoundedTBm then try deleting the config file at `%localappdata%\rtb.json` (or if you're using the Store version, the delete the file at `%localappdata%\Packages\14082CryzenTechnologies.RoundedTB_6b5yntewjra3r\RoamingState\rtb.json`). Re-open it, see if it launches.

**Comment by erad2008** [comment]
Hi. Thanks for the tip. I am away from home for a few days but will try when I get back. Thanks again

**Comment by aizuchan** [comment]
> 

Deleting the config file seems to fixed the issue. (I restarted windows explorer as well just to be sure)

Thank you for your time! My desktop looks slick again :D

**Comment by erad2008** [comment]
Hi. Just wanted to let you know. I am home and tried deleting the config file and now is all working again. Thanks again for your help. 👍

**Comment by Erisa** [comment]
Thank you for confirming!
