### ISSUE TITLE
"System Tray" doesn't work on Windows 11

### ISSUE THREAD

**Issue by Abdiel-Maldonado-Gonzalez** [torchgm/RoundedTB#187]
I am using two monitors and I need to see the date and time section on both monitors, although I have "System Tray Win+F2" activated and it works perfectly on the main monitor, nothing happens on the secondary monitor. I can only see the date and time when I fully maximize the window and the task bar is filled.
It would be very helpful if the System Tray worked correctly on both monitors. 

Without more to add, I congratulate you for your application, it gives a pretty nice touch to the Windows desktop.

**Comment by Erisa** [comment]
This feature will be added in the next update.

The problem is tracked in #138, so this duplicate issue will be closed.
