### ISSUE TITLE
Startup time slow. 

### ISSUE THREAD

**Issue by parth25sareen** [torchgm/RoundedTB#188]
Whenever I boot my pc everything loads and then RoundedTb loads after a min or so. Please improve the loading time speed :)
Thanks.

**Comment by torchgm** [comment]
The speed at which an app runs on startup is controlled by Windows. Apps registered to start when a user logs in are configured with a 10-second delay.

There's some information on altering this delay here: https://www.howtogeek.com/403162/how-to-disable-the-windows-10-startup-delay/
