### ISSUE TITLE
Add please multiscreen

### ISSUE THREAD

**Issue by strongenough07** [torchgm/RoundedTB#189]
thank you

**Comment by Erisa** [comment]
What do you mean?

**Comment by strongenough07** [comment]
![IMG_20220305_165758.jpg](https://user-images.githubusercontent.com/79000625/156888737-a967442c-4678-49c2-b7a9-e43f418fab4d.jpg)![IMG_20220305_165805.jpg](https://user-images.githubusercontent.com/79000625/156888740-5732c8d8-4d10-49bd-bc93-01a9157e0ece.jpg)

**Comment by Erisa** [comment]
Do you have autohide enabled? Autohide is currently not supported but will be in the next release.

**Comment by strongenough07** [comment]
Yes working fine with auto hide

**Comment by Erisa** [comment]
This bug you are reporting only happens when you have autohide enabled.

This is tracked further in #36 and will be fixed in the next update (R4)
