### ISSUE TITLE
RoundedTB 1.3.1.0 Dynamic Mode not working on 22572.201

### ISSUE THREAD

**Issue by dudeisbrendan03** [torchgm/RoundedTB#193]
Hi all,
Using outer margin on dynamic mode with show system tray on hover will cause the system tray to not appear properly (see below)
![image](https://user-images.githubusercontent.com/6009600/158890357-136a0a8d-9312-47ad-932a-f1ff7aec42a5.png)

Due to the outer margin being applied on the (hidden) system tray.
I believe that the outer margin should not be applied to the right margin (only the left outer margin) when this mode is on so the system tray is completely visible when enabled.

**Comment by dudeisbrendan03** [comment]
Something may be wrong with my install, applying the same settings as the image on the README results in this (I disabled the weather widget now as it may have been causing issues, but to no effect)
![image](https://user-images.githubusercontent.com/6009600/158890853-454168bf-42d0-495b-a1a2-6ac6ea447f1f.png)
![image](https://user-images.githubusercontent.com/6009600/158890866-c60dd96e-fc47-426d-ad33-64f0fbd0eb4a.png)

**Comment by dudeisbrendan03** [comment]
![image](https://user-images.githubusercontent.com/6009600/158891806-da6d3af5-2079-4130-a332-8998c8908bd7.png)
Dynamic mode is not working properly, winver attached (roundedtb 1.3.1.0)
![image](https://user-images.githubusercontent.com/6009600/158891991-443f5fbb-e677-496e-92a2-b92e847a7ffc.png)

**Comment by dudeisbrendan03** [comment]
![image](https://user-images.githubusercontent.com/6009600/158892442-1badd19a-ee98-473f-88aa-ec56ff9693cb.png)
Sorted!

**Comment by Erisa** [comment]
For future reference, marking as duplicate of #98
