### ISSUE TITLE
Dynamic Mode extends to the left.

### ISSUE THREAD

**Issue by clickers331** [torchgm/RoundedTB#195]
When I installed Rounded TB, I had widgets on (I guess a default feature on a new update to win 11) and it made it so that the rounded cornered floaty thingy extended left on dynamic mode. I tried disabling widgets but the result was the same.
![image](https://user-images.githubusercontent.com/61944296/159751973-58e75d22-5831-47ff-ad3c-49ae7332a10a.png)

**Comment by Erisa** [comment]
This is tracked in #98, is fixed in Canary builds and will be fixed in the next update.

To resolve it for now, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".
