### ISSUE TITLE
Dynamic mode isn't working properly

### ISSUE THREAD

**Issue by Mikaks** [torchgm/RoundedTB#196]
![image](https://user-images.githubusercontent.com/75081159/160177067-53511976-0f1a-4ce9-b66b-de8f2e80dd35.png)

**Comment by Erisa** [comment]
You may have realised already but just to clarify:

This is tracked in #98, is fixed in Canary builds and will be fixed in the next update.

To resolve it for now, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".
