### ISSUE TITLE
Add transparency mode

### ISSUE THREAD

**Issue by clownstudios** [torchgm/RoundedTB#199]
Please add transparency mode like translucent tb orlively wallpaper.

**Comment by Erisa** [comment]
No. This is out of scope for RoundedTB.

If you want trasparency, install TranslucentTB yourself and use it alongside RoundedTB. There is a compatibiility mode in RoundedTB settings to make the two apps work together properly.

**Comment by clownstudios** [comment]
Ok. Thanks
