### ISSUE TITLE
roundedTB works on the right side, but on the left side, its filled and not round.

### ISSUE THREAD

**Issue by GalaxyLord44** [torchgm/RoundedTB#200]
roundedTB works on the right side, but on the left side, its filled and not round
![Screenshot 2022-04-09 204147](https://user-images.githubusercontent.com/70305637/162568492-7f763b08-e875-4ac0-835c-46ff5676b505.png)
.

**Comment by Erisa** [comment]
This is tracked in #98, is fixed in Canary builds and will be fixed in the next update.

To resolve it for now, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".
