### ISSUE TITLE
Line on bottom in autohide

### ISSUE THREAD

**Issue by MichiBab** [torchgm/RoundedTB#206]
Hi,
there is a line free on autohide. It seems to be just 1 or 2 pixels off to be in fullscreen and you can see the background. I am using the canary build RoundedTB-4c8cb26,
![Screenshot 2022-04-22 163358](https://user-images.githubusercontent.com/45234706/164735958-2e8de6be-8399-4b29-b4d1-2b222d2ea00e.png)
The image is taken from the browser, it happens on other applications aswell. Hovering on it puts the cursor in the drag state, for resizing.

**Comment by torchgm** [comment]
This has to be there due to how Windows works - if a Window takes up 100% of the screen it is considered "fullscreen" which in turn prevents the taskbar from appearing above it.
