### ISSUE TITLE
RoundedTB crashes at startup

### ISSUE THREAD

**Issue by bricksdagamer** [torchgm/RoundedTB#21]
I'm using the Windows Store version. How do i fix it?

**Comment by torchgm** [comment]
Absolutely no idea - I was a huge idiot and deployed the first Store version without the necessary debug symbols for troubleshooting. Next version will have proper debug symbols and logging.

Troubleshooting steps for the Store version right now though are to just reinstall it, and make sure you've not got any other taskbar modifications at the same time. Whilst there shouldn't be any app-crashing issues with them, I've not been able to test compatibility with every single thing.

If it works without any other taskbar tweaks/mods, then let me know what else you were using. If you don't have any other taskbar mods, can you let me know your OS build, edition and architecture? You can find all this by pressing <kbd>Win</kbd>+<kbd>Pause|Break</kbd>.
