### ISSUE TITLE
Not working at all on left side!

### ISSUE THREAD

**Issue by bromelio** [torchgm/RoundedTB#212]
This would be a great app if only it was working correctly. Unfortunately, however, dynamic mode simply doesn't work on the taskbar's left side: while it's right side is correctly cut at the right border of the rightmost app, the taskbar's left side still goes all the way to the left edge of the screen just like it would without using this app.

**Comment by Erisa** [comment]
This is tracked in #98, is fixed in Canary builds and will be fixed in the next update.

To resolve it for now, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".

**Comment by bromelio** [comment]
> This is tracked in #98, is fixed in Canary builds and will be fixed in the next update.
> 
> To resolve it for now, go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".

Thanks for the super-fast replay. Yes, please fix it with the next update, this would do RoundedTB very good!
