### ISSUE TITLE
cant open taskbar with hovering over it

### ISSUE THREAD

**Issue by SpontanaKAk** [torchgm/RoundedTB#213]
Maybe it is a bug or it is intentional that you can't open the taskbar with hovering on the bottom. You could also add a feature to enable or disable it because i couldnt open it on my desktop nor in browser or other apps.

**Comment by Erisa** [comment]
Taskbar autohide is not supported in the latest version, but is supported in the canary version (Which is unstable)

This is tracked and discussed in #36
If that isn't your issue, just reply here.
