### ISSUE TITLE
Staying In Same Taskbar position when in dynamic mode.

### ISSUE THREAD

**Issue by Tuwtler** [torchgm/RoundedTB#219]
When I go in dynamic mode the taskbar stays at the bottom instead of being like the "mac ui" and going on top of the app or dissapearing properly.

![image](https://user-images.githubusercontent.com/100053240/168933868-0585b6e5-2188-4c5d-8da8-0453f2008900.png)

**Comment by torchgm** [comment]
This is intentional and why the "Fill taskbar on maximise" option was added. A future update will provide the ability to have the taskbar overlap the active window.
