### ISSUE TITLE
Jagged rounded corners on Windows 11

### ISSUE THREAD

**Issue by wmyfelix** [torchgm/RoundedTB#22]
with 4k monitor

**Comment by torchgm** [comment]
Yep, this is documented and known. There's really not much that I can personally do about this - the alternatives involve either making the taskbar transparent then drawing under it or performing complex rendering on the taskbar itself, both of which would be inherently less stable than the solution I've chosen. It's annoying but personally I've found that the lack of antialiasing isn't a huge issue imho.

Right now there's no plans to change this, but if I do find a magical solution in the future then I'll be sure to implement it.
