### ISSUE TITLE
[Feature Request] Please add WinUI3 & Windows 11 design 

### ISSUE THREAD

**Issue by Shahriyar-Asghari** [torchgm/RoundedTB#227]
It seems that Win UI 3 was not used in the design of this program. It would be great if the new design of Windows 11 came to this program and the taskbar changes were done with cool animations.

**Comment by Erisa** [comment]
WinUI 3 design has been implemented and is available in the current Canary builds and the next released version.

You made a separate issue for animaitions (#226) so I will close this one.
