### ISSUE TITLE
Taskbar Pseudo-transformation issue

### ISSUE THREAD

**Issue by 0megaplus** [torchgm/RoundedTB#229]
When applying settings from RoundedTB on Windows 10, the taskbar buttons, like the Windows key update, but not for the taskbar _itself_. 
</br>I went through the tutorial and everything, and restarted Windows, but nothing changes. Sometimes the taskbar will undo the changes, even with the RoundedTB open. I have the Store version.

This picture shows the Windows button highlighted, showing the issues:
![Screenshot 2022-06-06 122116](https://user-images.githubusercontent.com/97362960/172233516-20099b69-8f78-4b47-997b-a3476a2ff84e.png)

Any info for this helps,
Omega207
(If this a duplicate, I'm sorry, I don't want to look through 100+ issues with different titles. Please direct me to the original issue with the problem if that is the case.)

**Comment by Omega207** [comment]
Nevermind, the issue eventually fixed itself.
