### ISSUE TITLE
Date and time getting cut off

### ISSUE THREAD

**Issue by nvonbenken** [torchgm/RoundedTB#23]
![image](https://user-images.githubusercontent.com/6497977/127258857-53e355f1-807a-43b6-a925-6ad1444d4aee.png)

Any way to single line the date/time or any other alternative so these don't get cut off?

**Comment by torchgm** [comment]
There's nothing I can do about this from RTB but you can use [T-Clock](https://github.com/White-Tiger/T-Clock/) to highly customise the appearance and functionality of your clock to better-fit within-bounds.
