### ISSUE TITLE
The taskbar is splitting to 2 instead of 3 segments in dynamic mode (Win11 Build 220610).

### ISSUE THREAD

**Issue by muzscaly** [torchgm/RoundedTB#232]
Related to #138 .
The feature is now broken in newest build of Windows 11 (220610).
The widget segment is connected with main segment. While icon tray segment remains splitted from the rest.
![image](https://user-images.githubusercontent.com/15150065/174604255-5d3c7638-5126-4810-ae9f-b5f8e28c7642.png)

**Comment by Erisa** [comment]
Can you try: go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".

**Comment by muzscaly** [comment]
> Can you try: go to Windows' Taskbar Settings, and change taskbar alignment to "Left" and then back to "Center".

Huh... That worked. Odd that it doesn't work the first time, only after changing taskbar allignment and back in Settings.
