### ISSUE TITLE
Multiple Monitor Support

### ISSUE THREAD

**Issue by voodoomsr** [torchgm/RoundedTB#233]
Is there a plan (or workaround) to support multiple monitor?

At least on my initial usage this only works on main monitor leaving the taskbars on other monitors untouched.

**Comment by kerimgrande** [comment]
If you are on Windows Insider Builds, there is no workaround for that. RoundedTB isn't optimized for the new taskbar in 22H2. The only way to get it to work again, is to leave the Insider channel.

**Comment by voodoomsr** [comment]
I'm not in insider, regular 21H2. I don't know if you get the issue. Is just that in any extra monitor, beside the main one, the taskbars are unnafected.  Looks like the program only modifies the main monitor one.

**Comment by kerimgrande** [comment]
Sorry that I took so long to reply. This bug has happened (or is still happening) to me too. I've talked to Torch (creator) on Discord once and he told ne that he will fix it as soon as he is done with his break. You can leave this issue open until it's fixed.

**Comment by kerimgrande** [comment]
something just came to my mind. have you tried the dev/canary versions if they support multiple monitors? lmk if it works! you can find them somewhere in this repository.

**Comment by voodoomsr** [comment]
Hi @kerimgrande I believe it was a problem on my end. I was using another app that is called Transparent Taskbar pro. Somehow it produces a conflict. After I restarted having the mentioned app disabled, this app started working fine.
My second monitor shows the rounded taskbar perfectly.
Sorry for the confusion. Nice work btw, I will have this permanently on, looks amazing.

**Comment by kerimgrande** [comment]
So glad it worked! You can close this issue now.
