### ISSUE TITLE
Dynamic mode bug

### ISSUE THREAD

**Issue by kmk709** [torchgm/RoundedTB#24]
I cann't correctly split the task-bar like the screenprint in the release. System tray split is running great. The blank on the left side of Windows icon still shows.
![image](https://user-images.githubusercontent.com/58921795/127316931-73e560ae-8a8a-47ec-b741-2cff65154fb5.png)

**Comment by kmk709** [comment]
Program runs on Windows 11

**Comment by torchgm** [comment]
As mentioned in the prerelease, don't file issues regarding P3.0. I'm already aware that these bugs exist and made it very clear that it will be buggy if you choose to use it. I'm looking into fixing them already, and will have a more stable prerelease in the future.
