### ISSUE TITLE
Feature Request(sparkles): Centred Taskbar with Invisible Background 

### ISSUE THREAD

**Issue by kkanekii** [torchgm/RoundedTB#25]
Title should explain it,  something like taskbarx should be a feature, I'll switch over to roundedtb if someone could get this done

**Comment by torchgm** [comment]
This is out-of-scope for RoundedTB and won't be happening. Centred taskbar functionality is available on Windows 10 using TaskbarX and on Windows 11 natively. Furthermore TranslucentTB (and TaskbarX to a lesser extent) already offer the ability to customise the background of the taskbar, making it entirely transparent if you wish, and I have no plans on competing with either of these tools.

**Comment by francescomosca** [comment]
> and I have no plans on competing with either of these tools.

Maybe you could try to collaborate with TaskbarX dev ( @ChrisAnd1998 ) as you did with TranslucentTB?
I think that this could even resolve the need to use the Desktop workaround for the Split Mode if TranslucentTB could "announce" the new taskbar position

**Comment by torchgm** [comment]
Split mode is an interim whilst I look into getting a full version of dynamic mode working on Windows 10. Don't worry, it will be coming and it should also support TaskbarX. Any composition effects however are currently causing issues; TranslucentTB has an upcoming update that adds a workaround that I can use but it's not perfect, and TaskbarX would need some changes for the same workarounds to be implemented there.

The issue at hand was if I was going to implement options for centred icons and custom compositions, and the answer is still no; there are other tools (Like TTB and TBX) that do it a lot better, and I'll try my best to make sure RoundedTB works with them wherever possible.
