### ISSUE TITLE
RoundedTB in 22H2 won't remove this unused part in the left side

### ISSUE THREAD

**Issue by pGbSean** [torchgm/RoundedTB#252]
![image](https://user-images.githubusercontent.com/97381104/194736142-2d2124ae-357a-438f-bc0b-c9ee474b56a4.png)

I think this bug occurs because of the weather widget in the left. Turning off the weather widget still occurs.

![image](https://user-images.githubusercontent.com/97381104/194736179-f8eaa073-aaf8-4829-9411-8fb791768c55.png)

**Comment by Darkham42** [comment]
Same here, solved by changing Taskbar aligment.
In Settings > Personalisation > Taskbar aligment. Choose Left and go back to center, worked for me, hope it'll fix yours.

**Comment by lightningquick** [comment]
@Darkham42 thanks for that. Really helped out. Had no idea why that was happening. Hopefully they fix it.

**Comment by pGbSean** [comment]
> Same here, solved by changing Taskbar aligment. In Settings > Personalisation > Taskbar aligment. Choose Left and go back to center, worked for me, hope it'll fix yours.

Really worked! Thanks!
