### ISSUE TITLE
Multiple instances of RTB can run at the same time

### ISSUE THREAD

**Issue by heftymouse** [torchgm/RoundedTB#3]
The title pretty much. They all affect the taskbar and the app keeps the settings of whichever instance closes last.
![image](https://user-images.githubusercontent.com/59918974/120333610-7cc1d100-c30d-11eb-9e8d-4a67ffaad486.png)

**Comment by torchgm** [comment]
This was left-in for testing lol, but yeah I'll get around to patching this out soon enough.

as a temporary mitigation, don't open it more than once?

**Comment by torchgm** [comment]
Hi there, e8cb2c7 fixes this issue and will be live in R3.0.
