### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by thaynos** [torchgm/RoundedTB#32]
i tried both the ms store version which never even launched and the github release but both dint work. the apply button wasnt "clicking" and dint leave any changes

**Comment by torchgm** [comment]
Did you enter any values into the Corner Radius and Margin boxes, and are you using any other taskbar modifications such as TranslucentTB or TaskbarX?

**Comment by thaynos** [comment]
im using taskbarx and i did enter values but i wasnt able to click enter
button

**Comment by torchgm** [comment]
In what sense weren't you able to click it? If you're using the transparency effects provided by TaskbarX then a bug with DWM prevents the changes from showing up until the start button is clicked (like actually clicked with the mouse, it's a really odd bug). There's a mitigation for this bug (not a full fix unfortunately, that's out of my control) coming in the next update, but try clicking Apply then clicking the Start button a couple of times.

**Comment by thaynos** [comment]
no i literally cannot click on the apply button thats what i meant by enter
sorry

**Comment by thaynos** [comment]
im trying to click it but nothing happens...
https://user-images.githubusercontent.com/83282129/131563988-5adcf7b4-a7bb-440d-a3bc-adf3654257a6.mp4

**Comment by torchgm** [comment]
I can tell from the video that you are clicking it fine and the button is working. Your grey accent colour is almost identical to the colour of the clicked button however, so it's just really hard to see. As for why it's not doing anything, again are you using any other taskbar modifications as you weren't clear in your previous response?

**Comment by thaynos** [comment]
i only have taskbarx and wallpaper engine

**Comment by torchgm** [comment]
Do you have any transparency effects applied in TaskbarX? These are known to cause issues at the moment.

**Comment by thaynos** [comment]
Yeah, I do.

**Comment by thaynos** [comment]
but i tried disabling taskbarx completely it still dint work.
