### ISSUE TITLE
Feature Suggestion: Allow us to adjust the position of the taskbar

### ISSUE THREAD

**Issue by fillwithjoy1** [torchgm/RoundedTB#33]
I love the app, it's great. However the margins just compresses the taskbar which makes it feel weird at times. Is it possible to create a y offset setting so we can just have the taskbar more visible?

**Comment by torchgm** [comment]
Unfortunately as mentioned in #17, Windows prevents the taskbar from actually being moved freely by other applications, making this more-or-less impossible.

**Comment by fillwithjoy1** [comment]
Is it possible to crop this?
![image](https://user-images.githubusercontent.com/29514446/131926541-11df9db7-c51b-4ccb-9d4a-e5b649b2401e.png)

**Comment by torchgm** [comment]
This functionality will be available in RoundedTB R3.

**Comment by torchgm** [comment]
This functionality is now available in R3 on both the Store and GitHub.
