### ISSUE TITLE
[Feature Request] Add a smart hide feature

### ISSUE THREAD

**Issue by Spontini** [torchgm/RoundedTB#34]
Hello, I think it'd be cool if the task bar is hidden if we have something in full screen and not hidden if we don't have anything in full screen (just like in MacOS basically).

**Comment by sumitankitg130** [comment]
Also when we use auto hide taskbar, it gets very glitchy.

**Comment by torchgm** [comment]
As mentioned in other issues, Autohide is indeed incredibly buggy and currently not supported. I'll be building a custom autohide feature that optionally implements this suggestion and also mitigates the issues that occur with Windows' autohide.

**Comment by JoshuaLeivers** [comment]
Having the autohide feature work would be perfect, but also alternatively it'd be great if it was possible to have maximised windows go fully to the bottom of the screen when in dynamic mode, so you can actually use the space it frees up by segmenting the taskbar

**Comment by Erisa** [comment]
Going to close in favour of #36 and Torch saying that the eventual autohide implementation will have this suggestion.
