### ISSUE TITLE
UI broken when input method changes

### ISSUE THREAD

**Issue by jwdotpark** [torchgm/RoundedTB#35]
![image](https://user-images.githubusercontent.com/38537908/132097899-5c77706b-3464-4bd7-8377-15e009a813df.png)

![image](https://user-images.githubusercontent.com/38537908/132097892-b42ee8bc-a85d-4a1b-95cf-5757206fde30.png)

W11 beta channel 22000.176

It seems dynamic mode UI gets broken when systray refreshed(option change), in my case it was when I toggled language bar in systray. 

If I toggle the second option ` Use the Desktop language bar when it's available `  it reverts back to normal.

![image](https://user-images.githubusercontent.com/38537908/132097958-8561a67a-70b6-4903-94ca-8602fbfcc5e9.png)

Hope this helps!

**Comment by torchgm** [comment]
Ah yes, this issue. on P3 this was quite common. I've just prereleased [P3.1](https://github.com/torchgm/RoundedTB/releases/tag/P3.1) which should have fixed the issue. If you could test it to see if you can still reproduce, that'd be appreciated!

**Comment by jwdotpark** [comment]
It's still needed to be toggled on and off to make it work as intended, but it rarely happens to be honest. It's just set and done for good thing, no worries.

All in all It's pretty stable so far, I'd almost never seen it broken for weeks. Thank you for the upgrade though!!

**Comment by torchgm** [comment]
Hopefully these issues should be mostly resolved now - however this sounds like it was one of the weird few Windows issues that causes the taskbar to "stick" for seemingly no reason in a way that's not actually possible to detect. Let me know if this needs addressing further.
