### ISSUE TITLE
How to change RoundedTB settings after closing app and hiding tray?

### ISSUE THREAD

**Issue by Cyberdroid1** [torchgm/RoundedTB#42]
After hiding the system tray and closing the settings window, I am not able to unhide the system tray again, and because of that, I cannot even change RoundedTB settings now. 
Sure, I can kill roundedtb via taskmgr and restart explorer to get back the tray, but I am finding it difficult to access the settings now :/

Is there a way to access setting some other way? I tried running the exe file again, but it just said that one instance of RoundedTB is already running. 
I would also like to request the functionality of opening settings by opening the exe file again incase RoundedTB is already running.

**Comment by torchgm** [comment]
If you're using a prerelease build past P3.0 (so P3.1 or a canary build released after P3.0), then you can press <kbd>Win</kbd>+<kbd>F2</kbd> to hide and show the system tray. This information will be documented in the readme as well as in-app when R3 launches, and will probably be a customisable keybind in R4.

> I would also like to request the functionality of opening settings by opening the exe file again incase RoundedTB is already running.
Good suggestion! Not 100% sure if I can squeeze it into R3 now, but I'll certainly try my best to implement it.

**Comment by Cyberdroid1** [comment]
> you can press Win+F2 to hide and show the system tray. 

Thank you! 

> Good suggestion! Not 100% sure if I can squeeze it into R3 now, but I'll certainly try my best to implement it.

Looking forward to it! 😄

**Comment by torchgm** [comment]
Opening the app again now launches the settings, as of R3.1.  The tray is also optionally accessible on hover.
