### ISSUE TITLE
Taskbar isnt dynamic with TranslucentTB enabled

### ISSUE THREAD

**Issue by 541880748** [torchgm/RoundedTB#45]
When opening apps outside of pinned to taskbar apps with TranslucentTB enabled, the taskbar doesn't change

**Comment by torchgm** [comment]
This functionality requires "TranslucentTB Compatibility" to be enabled, which in-turn requires TranslucentTB version 2021.5. As of right now, this version isn't available. Once it is available, this option will become functional. You can read more in the dialog presented to you when you enable the TranslucentTB Compatibility option.
