### ISSUE TITLE
Add option for maximized apps to maximize (go) under (behind) the taskbar

### ISSUE THREAD

**Issue by MAXYMOK** [torchgm/RoundedTB#46]
![Screenshot 2021-09-27 231739](https://user-images.githubusercontent.com/81030114/134980120-8797a9eb-ae32-495d-b8c3-bebaaa33a7bd.png)

**Comment by torchgm** [comment]
I'm not sure how possible this is - I have some ideas to try and "fix" autohide (at least make it less flickery), but keeping the taskbar out of the work area whilst also having it always-on-top seems like the kind of thing that shappbar will refuse to let me do. I'll have a look, but no guarantees.

**Comment by ace-wolf** [comment]
I would love to see this feature too! :)

**Comment by torchgm** [comment]
Closing to instead keep track of this suggestion and many more in #36
