### ISSUE TITLE
Windows 11 Dynamic Mode doesn't cut left side

### ISSUE THREAD

**Issue by Ryah** [torchgm/RoundedTB#51]
![image](https://user-images.githubusercontent.com/14987609/135148534-3347baa5-cee3-4fcd-909b-4335c0239de8.png)

**Comment by torchgm** [comment]
This is a bug that will either be corrected in an upcoming update - very simple fix for now, just set the taskbar alignment to the left, then back to the centre; after that you shouldn't see this odd behaviour anymore.
