### ISSUE TITLE
Suggestion: Hover to reveal 

### ISSUE THREAD

**Issue by xtprion** [torchgm/RoundedTB#57]
I love this apps, it's play nice with translucentTB and windows 11 (albeit with some bugs).

One suggestion from me: I think it would be great if this apps have "hover to reveal" system icon, so it's basically disappear unless you hover into the systray area.
I also heard that you're working in some auto-hide functionality? This is not only a great news for me, but also make new possibility, that activating the auto hide from certain place will activate the systray, but not when it's triggered on other place (like from the bottom center)

**Comment by torchgm** [comment]
Not 100% sure what the possibility of that would be like but I can certainly look into it. And yes, I am indeed working on a better autohide feature to replace Windows'. I'll see what I can do.

**Comment by moisesremoto** [comment]
nice, i just downloaded rounded tb and my main problem was how autohide basicly doesnt work, cant wait for it to work :)

**Comment by torchgm** [comment]
As of R3.1 the tray now has hover-to-reveal functionality.

**Comment by moisesremoto** [comment]
YESSS TYSMMMMM

**Comment by xtprion** [comment]
> As of R3.1 the tray now has hover-to-reveal functionality.

Thanks for the feature sir, it works perfectly with my setup now xD
