### ISSUE TITLE
Taskbar is left anchored

### ISSUE THREAD

**Issue by gemx** [torchgm/RoundedTB#60]
It's best shown in the screenshot.
The visible taskbar should only behind the icons in the center as i understand but why is the taskbar visible on the whole left side?

![image](https://user-images.githubusercontent.com/1876307/136177580-f7458089-8d41-457c-9609-8e4a910412e0.png)

**Comment by iRhysLee** [comment]
You need to go into Taskbar Settings and toggle left aligned taskbar and then back to centred and it should fix.

**Comment by gemx** [comment]
Thanks. Great. 
That did the trick :-)

**Comment by torchgm** [comment]
Worth noting this bug was fixed in a recent commit and will be released as part of a collection of stability/performance improvements soon.
