### ISSUE TITLE
Left Side not shrinking to appropriate size in Dynamic mode.

### ISSUE THREAD

**Issue by ghost** [torchgm/RoundedTB#61]
![image](https://user-images.githubusercontent.com/65875803/136490731-f137db8d-c80d-46f7-84b2-a1aefd2afe39.png)
Running on Windows 11, with dual graphics (intel and nvidia). 

Changing Inner and Outer Margins don't seem to change where the left and right sides reside. Although these may have nothing to do with what I am seeing.
![image](https://user-images.githubusercontent.com/65875803/136490946-f6e08ad4-ca76-4f3e-808f-43f10c7b07c0.png)

**Comment by ukashazia** [comment]
same here
