### ISSUE TITLE
System tray has blank space

### ISSUE THREAD

**Issue by ghost** [torchgm/RoundedTB#64]
Love the tool with 11 so far and looking forward to taskbar hiding. My only issue is that the system tray has a blank space on the right hand side and ruins what could be a super clean UI.

**Comment by flow2401** [comment]
Isn't the blank space the area of the (missing) notification assistant icon?
![image](https://user-images.githubusercontent.com/28014812/137368026-2d17322c-0e7c-4667-b374-a40680563515.png)
