### ISSUE TITLE
RoundedTB + Lively Wallpaper causes computer to freeze completely

### ISSUE THREAD

**Issue by MrConorAE** [torchgm/RoundedTB#65]
Launching RoundedTB and Lively Wallpaper at the same time causes the computer to freeze completely. No input is accepted, and I had to force shut down the device (holding the power button).
Lively Wallpaper has the "change taskbar appearance" option ON ([see screenshot](https://user-images.githubusercontent.com/26195325/136733003-14414d72-9d90-4388-b7e9-a2decd7a3da7.png)) - is this causing the issue?

Thanks :)

**Comment by torchgm** [comment]
The issue in question here was a bug with Windows itself. I might add partial compat in the future although for now it's just a case of using TranslucentTB if you want to make the taskbar, well, translucent.
