### ISSUE TITLE
About automatic hide taskbar.

### ISSUE THREAD

**Issue by PHalfStudio** [torchgm/RoundedTB#70]
This software has a bug. When the software's Dynamic mode is turned on, turn on the taskbar auto-hide option. When the taskbar is automatically retracted, the taskbar will flash.
My system is Windows11 22000.194. The problem can be reproduced. My English is not very good, so I use Google Translate. By the way, thank you for bringing us such a good software.

**Comment by torchgm** [comment]
Duplicate of #36 and #54, but summary is that Windows' autohide sucks, I won't ever be able to properly support it, and I'm working on a better replacement for it with more customisation.
