### ISSUE TITLE
When Dynamic Mode is enabled, the Start Menu's shadow is too sharp

### ISSUE THREAD

**Issue by shay4567** [torchgm/RoundedTB#71]
It's especially clear on a light background, it still looks like the shadow cuts off for the taskbar, even though it's not there, I suggest adding an option to remove the shadow entirely.
My settings here are: 
margin 4
radius 26
dynamic mode 
show system tray 
translucentTB compatibility
![2021-10-19](https://user-images.githubusercontent.com/71399805/137866732-56835e2d-4ec3-4ccf-93d2-f2787d0e4131.jpg)

**Comment by torchgm** [comment]
Unfortunately without XAML diagnostics (something that I really don't have a proper grasp on and is very badly documented), there's no way to remove that shadow. Even if you turn off window shadows it'll stay present for some reason. Right now, there's nothing I can do about this I'm afraid.
