### ISSUE TITLE
oh, noes!  if using RTB, one loses ability to use Peek button

### ISSUE THREAD

**Issue by emrys001** [torchgm/RoundedTB#8]
Even when using a radius of 1, if RoundedTaskBar is enabled at all, the button for peeking at the desktop that's normally found at the far right end of the TaskBar vanishes, ne'er to be seen again, or at least, until you turn RTB off, anyway.

otherwise, i think it's a really nice feature!  please teach RTB to play nicely with the other W10 features, 'cuz I'd really like to be able to use them both, simultaneously!

thanks **EVER** so much!!

**Comment by torchgm** [comment]
Hi there! This button is intentionally removed for now because it ends up looking absolutely awful. I'll add a checkbox to hide/show it in the next release. Thanks for the feedback!

**Comment by emrys001** [comment]
#response_container_BBPPID{font-family: Calibri, sans-serif; font-size:12pt; color: #1F497D;}  I can see where that could cause issues for this app (my career was as a software dev).  Could you "fake" it, maybe, and throw a button onto the other side of the tray, to activate the window-blanking?  You probably wouldn't be able to emulate the mouse-over effect, but so what?  People would cope...  (I did not do any coding of Windows apps, per se, so forgive me if I'm suggesting something that's not even remotely doable.  My big "windows app" was a huge, ugly beast of a Java application, that was launched via a .jnlp file.)Thank you very much, by the way,, for the direct reply... that's a nice touch, that I don't see many younger developers incorporating into their professional toolboxes!                                                                                                                                             -- m                                                                                                                                                                           From: ***@***.***Sent: June 13, 2021 1:48 PMTo: ***@***.***Reply-to: ***@***.***Cc: ***@***.***; ***@***.***Subject: Re: [torchgm/RoundedTB] oh, noes!  if using RTB, one loses ability to use Peek button (#8)  
Hi there! This button is intentionally removed for now because it ends up looking absolutely awful. I'll add a checkbox to hide/show it in the next release. Thanks for the feedback!

**Comment by torchgm** [comment]
Oh, I'm 11/10 exaggerating about how awful it looks; I just really wasn't a fan of the aesthetic at all (since if the taskbar corners are too rounded, the separator line gets cut off). Just adding a checkbox to show it won't be hard, and I should also be able to "show" it with a very low opacity so it's still there but you don't really see the ugly separator line. It's a good suggestion, thanks for bringing it up! For now, you can use the <kbd>Win</kbd>+<kbd>D</kbd> keyboard shortcut to temporarily hide and show the desktop.

**Comment by emrys001** [comment]
#response_container_BBPPID{font-family: Calibri, sans-serif; font-size:12pt; color: #1F497D;}  Well, good, if I helped in any way, I'm glad to hear it!I'm in M$'s "alpha test" program (I just completely spaced on what they call it!), and they've made some eye candy changes to how things look in the taskbar (and other places, as well...), and your app fits in well with what *they* did.  (So well, in fact, that I'm guessing it was the absence of any desire to deal with this very issue, that caused them to not include what your RTB app does!)  What they should probably do, to address this correctly, is refactor that Peek button completely out of the Taskbar, entirely.  Turn on the option in Settings, and the Taskbar suddenly has a width of #MAX_WIDTH - 20, or however many pixels they want to allocate for the Peek button plus some padding on its left.I have, as I said, zero Clue Points™ regarding actual Windoze coding, but I really can't imagine it would be *that* difficult for them to deal with, properly.  Then again, it IS M$... they probably have that peeking code included inside the IRQ8-handler, or something like that!                                                                                                                                       Thanks for the Win+D mention... I try to make use of their hotkeys, but I run so many little utils that add their *own* hotkey combos into the mix, I'd bet there are at least 10 that currently exist that I absolutely would make use of, if only I could remember they existed!!  Even with PowerToys screen overlay, it's difficult, cuz I know some of my favorite gizmos override even what shows up *there*!!First-world problems...Anyway, thanks.  It's a nice app, and with Win+D, it's *very* handy!  Thanks again!      -- m                                                                                                                                                                           From: ***@***.***Sent: June 14, 2021 11:09 AMTo: ***@***.***Reply-to: ***@***.***Cc: ***@***.***; ***@***.***Subject: Re: [torchgm/RoundedTB] oh, noes!  if using RTB, one loses ability to use Peek button (#8)  
Oh, I'm 11/10 exaggerating about how awful it looks; I just really wasn't a fan of the aesthetic at all (since if the taskbar corners are too rounded, the separator line gets cut off). Just adding a checkbox to show it won't be hard, and I should also be able to "show" it with a very low opacity so it's still there but you don't really see the ugly separator line. It's a good suggestion, thanks for bringing it up! For now, you can use the Win+D keyboard shortcut to temporarily hide and show the desktop.

**Comment by valeriesykes** [comment]
Well, the "show desktop" feature was kind of invisible or meshed into the taskbar originally anyway. Could you not do the same with the rounded taskbar? 

For now Win+D it is. Thank you!

**Comment by torchgm** [comment]
> Well, the "show desktop" feature was kind of invisible or meshed into the taskbar originally anyway. Could you not do the same with the rounded taskbar?

Again, it's not that showing the button is ugly, it's just that the rounded corners will frequently clip with the button and just doesn't look very pretty; with the loss of Fitt's Law (something I can't really do anything about) I didn't deem the button necessary for now and intentionally chose to hide it. In the next update (which I'll get around to when I'm not insanely overworked) I'll add a toggle to show/hide it.

**Comment by valeriesykes** [comment]
> Again, it's not that showing the button is ugly, it's just that the rounded corners will frequently clip with the button and just doesn't look very pretty; with the loss of Fitt's Law (something I can't really do anything about) I didn't deem the button necessary for now and intentionally chose to hide it. In the next update (which I'll get around to when I'm not insanely overworked) I'll add a toggle to show/hide it.

Really appreciate the prompt response. :) I meant to ask is it possible to make the "show desktop" at the end of the rounded taskbar invisible? There is the tiniest space on the end next to the action center icon, those that used that feature always know to click at the very end to show desktop but it is not very visible at all, natively with windows 10. 

Either way, am a fan!

**Comment by awesomelewis2007** [comment]
> Well, the "show desktop" feature was kind of invisible or meshed into the taskbar originally anyway. Could you not do the same with the rounded taskbar?

>For now Win+D it is. Thank you!

You can use <kbd>Win</kbd> + <kbd>,</kbd> to use peek too but this dose a quick peek

**Comment by torchgm** [comment]
> Really appreciate the prompt response. :) I meant to ask is it possible to make the "show desktop" at the end of the rounded taskbar invisible?

The prompt response was just luck I'm afraid, I'm waaaaay too lazy most of the time 😅
And yes, it should be possible to make the button effectively invisible whilst still keeping it functioning, I'm just super-bogged down with IRL stuff right now so I've not had much time to work on stuff.

**Comment by valeriesykes** [comment]
> > Well, the "show desktop" feature was kind of invisible or meshed into the taskbar originally anyway. Could you not do the same with the rounded taskbar?
> 
> > For now Win+D it is. Thank you!
> 
> You can use Win + , to use peek too but this dose a quick peek

I'm a noob, I apologize. Thanks for the tip!

Will have to retrain my muscle memory. Having that hidden show desktop feature on a rounded taskbar could be nice for an average everyday windows. Keyboards shortcuts appeal to a certain crowd. ;)

**Comment by valeriesykes** [comment]
> > Really appreciate the prompt response. :) I meant to ask is it possible to make the "show desktop" at the end of the rounded taskbar invisible?
> 
> The prompt response was just luck I'm afraid, I'm waaaaay too lazy most of the time 😅
> And yes, it should be possible to make the button effectively invisible whilst still keeping it functioning, I'm just super-bogged down with IRL stuff right now so I've not had much time to work on stuff.

Understood. Just throwing a little idea as a little cloud floating your way.

**Comment by torchgm** [comment]
Hi there! Hiding the button has been removed as of f1e9822 and will be live in R3.0. This was done as in Windows 11 the button works differently, plus there's a toggle to hide it there anyway, so adding such a small feature specific to 10 didn't really seem worth it. If you're on 10 there's plenty of other software that can control its appearance and presence dynamically, for example [TranslucentTB](https://github.com/translucenttb/translucenttb).
