### ISSUE TITLE
Apps cut off if there are too many on taskbar

### ISSUE THREAD

**Issue by PixelStudios759** [torchgm/RoundedTB#83]
I have a lot of apps on my taskbar (yes I do use every one of them), but if you have enough on the taskbar, you can't even see the s t a r t  b u t t o n. I have tried to disable it for the time being but I'm not quite sure how. Please fix this, thanks
![issue12](https://user-images.githubusercontent.com/93302598/139180820-9ca474af-ec59-451f-92d3-3e6018fff736.png)
![issue1](https://user-images.githubusercontent.com/93302598/139180699-148d287d-c391-4137-afbb-4b6b4e126e39.png)

**Comment by torchgm** [comment]
This should now be resolved in R3.1 as described - let me know how it goes.
