### ISSUE TITLE
[Crash] DWM / Windows Explorer

### ISSUE THREAD

**Issue by DtZNimpo** [torchgm/RoundedTB#85]
This issue i'm not quite sure if it's related to RoundedTB or if it's W11 doing this. Microsoft have released an update which seems to be related to this current issue and after applying that update i was still having this issue. In both cases before and after i was using RoundedTB.

Issue: Randomly my desktop background will go from wallpaper to fully gray (windows color) the taskbar will be gone , pressing windows Key does not open Start menu , right clicking the desktop does nothing. DWM / Windows Explorer seems to have crashed and will not recover.

RoundedTB settings:
Margin 0
Corner Radius 10
Dynamic mode On
Show system tray (win+f2) On

screenshots of how it looks like vs how it should be.
https://imgur.com/a/W91IGae

**Comment by DtZNimpo** [comment]
NVM seems even without RoundedTB the issue persist, W11 is still in beta right ? :)

**Comment by lux1111** [comment]
My taskbar fully gray at every windows 11 start, even after uninstall. Only manually restarting explorer helps. I think this is related. I also have TranslucentTB. Making new user fixes this issue. I think this software modifies registry or something. DISM /restorehealth not helping.

**Comment by DtZNimpo** [comment]
i've found the cause of my issue , it was caused by the app named "SVP 4 PRO"  it's a third party app to make your video play at higher refresh rate with interpolation or whatever, when it's opened it would crash windows explorer randomly , with it off it doesn't affect it. The dev of the software in question also mentioned FFDSHOW can cause similar issue to windows explorer , uninstalling ffdshow should be advise until microsoft release a patch that may improve the situation with those 2 program , or those 2 program figure out a way to fix that particular issue....

As for RoundedTB i've tested with it on and with it uninstalled and both were giving the gray background no taskbar no start and having to restart windows explorer , but the issue was not related to RoundedTB it was just a coincidence. RoundedTB is clean on that front.

**Comment by torchgm** [comment]
Glad to hear you've resolved the issue! Flagged as invalid since it doesn't actually relate to RoundedTB, but hopefully if anyone else is having a similar issue then they might stumble across this issue, so thanks for documenting it anyway!!
