### ISSUE TITLE
RountedTB crashes when running with SmartTaskbar - Windows 11

### ISSUE THREAD

**Issue by khushrxnx** [torchgm/RoundedTB#86]
SmartTaskbar is a cool application to hide the taskbar when a window is maximized, in Windows 11

When RoundedTB and SmartTaskbar are running together for a maximized window, there is a continuous white line blinking at the bottom of the screen.

Also, RoundedTB crashes after sometime when running along SmartTaskbar no matter what a window size maybe (maximized or not)

**Comment by khushrxnx** [comment]
I have realized that the issue has been occurring due to the incompatibility of RoundedTB with Auto Hide in Windows 11.

Please fix this bug ASAP! Really appreciate it!

**Comment by torchgm** [comment]
Yup, as you've realised it's to do with autohide, and as I'm sure you've also noticed, I can't fix autohide. It's fundamentally broken as it directly conflicts with how Windows hides the taskbar. I'm just in the process of finishing up Release 3.1, and after that I'm going to be working on a custom autohide that will work completely differently.

This won't be compatible with Windows' own autohide, nor will it work with SmartTaskbar. However, it will have similar customisable functionality to allow you to hide the taskbar only when an application is maximised. No idea on how long it'll take I'm afraid, but it will be the next big thing I'm looking at.
