### ISSUE TITLE
Inner Margin in Dynamic Mode should be mirrored

### ISSUE THREAD

**Issue by Nesqulck** [torchgm/RoundedTB#87]
Currently in dynamic mode (and show system tray = On) the **inner margin** works such that margin >0 cuts the left part of the TB (start menu etc) but extends the right part of the TB (tray, clock etc). An inner margin <0 does the exact opposite, extends left part and cuts right part. I believe the more intuitive and useful way is to cut both parts if inner margin>0 and extend both if margin<0. Perhaps, a simple change of sign regarding the right part would make this possible. However, this is only applicable in dynamic mode.

**Comment by torchgm** [comment]
What version are you running? This was a bug in a few Canary/Dev builds but was fixed for the release of R3.

**Comment by Nesqulck** [comment]
Current MS Store version. R3 1.3.0.0 I believe

**Comment by torchgm** [comment]
Odd - I can't replicate this at all. Can you provide some screenshots w. settings that highlights this issue?

**Comment by torchgm** [comment]
Nevermind, I can! Wow, not sure how I missed that.

**Comment by torchgm** [comment]
Just fixed it, will commit shortly.

**Comment by torchgm** [comment]
Should be sorted now - give it a test if you get the chance and let me know if you still run into any issues.
