### ISSUE TITLE
Fill taskbar on alt-tab returned to disabled after rebooting system

### ISSUE THREAD

**Issue by pc-v2** [torchgm/RoundedTB#88]
Rounded TB : 
> RoundedTB-136dca2

Windows : 
> Windows 11 22000.318

**Comment by torchgm** [comment]
Huh - I was honestly debating whether or not I even add this option, so I probably just missed saving it or reading it back in properly. Thanks for highlighting the issue, I'll make sure it's fixed for R3.1.

**Comment by torchgm** [comment]
Should be sorted now - give it a test if you get the chance and let me know if you still run into any issues.
