### ISSUE TITLE
How can I set up to hide this part of the taskbar?

### ISSUE THREAD

**Issue by 3166265725** [torchgm/RoundedTB#90]
![屏幕截图 2021-11-12 104633](https://user-images.githubusercontent.com/61723005/141400368-4d219ad1-ee68-4787-adb9-46b629dce58c.png)

**Comment by torchgm** [comment]
This is a bug that's fixed in an upcoming update. For now, just set the taskbar icon alignment to the left then back to the centre from Windows' Settings app.
