### ISSUE TITLE
Hide taskbar idea

### ISSUE THREAD

**Issue by AndreySlower** [torchgm/RoundedTB#91]
so, i found the app called autohide desktop icons. it has an additional functionality to autohide taskbar, and it doesn't break roundedtb or translucentTB. i hope you can check it out and maybe it can somehow help.

**Comment by torchgm** [comment]
Not entirely sure what that software has to do with RoundedTB - however autohide now seems to partially work on some single-monitor configurations but not others. Regardless, I'll still be going ahead with developing my own custom autohide.
