### ISSUE TITLE
R3.1 Beta - Hovering over the tray does not work after logging-out and logging-back-in 

### ISSUE THREAD

**Issue by khushrxnx** [torchgm/RoundedTB#94]
R3.1 Beta is amazing and does wonders!

But this beta/sorta preview version has a bug that I wanted you to know about. When I hover over the tray with the hidden tray and hover-over tray settings, the hovering does not work after logging-out and logging-back-in (Windows button + L)

**Comment by torchgm** [comment]
Hm, I'm not able to replicate this - can you provide your config file? (Help & About > Debug > Open config file)

**Comment by MathiSmati** [comment]
Got a similar issue: sometimes hovering does not work anymore without any noticeable reason.
[rtb.log](https://github.com/torchgm/RoundedTB/files/7533698/rtb.log)
I am currently "fixing" this by maximizing a window(which maximizes the taskbar as well) so I can open rtb an re-enable this feature.

**Comment by pc-v2** [comment]
#100 ?

**Comment by MathiSmati** [comment]
Yup, my bad 😅
Thank you for letting me know that

**Comment by Erisa** [comment]
Closing because it was made for a prerelease and no debug data was given. Please respond with a config file or open a new issue with more information if you are experiencing this issue.
