### ISSUE TITLE
Make windows maximise under the taskbar

### ISSUE THREAD

**Issue by leo6720** [torchgm/RoundedTB#95]
I think it would be nice to have the option to maximise windows under the taskbar as if it was set to autohide. In this way you could use all the screen real estate you get from using rounded tb.

**Comment by leo6720** [comment]
I've just seen there was already a submission about this in the past sorry

**Comment by torchgm** [comment]
No worries, and this will be coming in the future - just takes a lot of work to rebuild a custom autohide feature.
